language: python

sudo: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

env:
  matrix:
    - TOXENV=py27-dj14
    - TOXENV=py27-dj15
    - TOXENV=py27-dj16
    - TOXENV=py27-dj17
    - TOXENV=py27-dj18
    - TOXENV=py27-dj19
    - TOXENV=py34-dj15
    - TOXENV=py34-dj16
    - TOXENV=py34-dj17
    - TOXENV=py34-dj18
    - TOXENV=py34-dj19
    - TOXENV=py35-dj18
    - TOXENV=py35-dj19
    - TOXENV=pypy-dj14
    - TOXENV=pypy-dj15
    - TOXENV=pypy-dj16
    - TOXENV=pypy-dj17
    - TOXENV=pypy-dj18
    - TOXENV=pypy-dj19
    - TOXENV=flake8

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_success: coveralls
